# Development environment configuration
# Extends base.yaml with development-specific settings

mcp_servers:
  servicenow:
    name: "ServiceNow Server (Dev)"
    command: "/PATH/TO/.local/bin/uv"
    args:
      - "--directory"
      - "/PATH/TO/servicenow-mcp-dev/src/servicenow_mcp/"
      - "run"
      - "--env-file"
      - "/PATH/TO/.env.development"  # Use dev-specific env file
      - "cli.py"

# Development-specific settings
development:
  debug: true
  log_level: "DEBUG"
  enable_tracing: true 